### ISSUE TITLE
Not all messages (notifications) are visible

### ISSUE THREAD

**Issue by marekmasek** [sannidhyaroy/Soduto#31] opened 2024-02-19 10:56 UTC
If I receive multiple messages on Instagram from one person then I can see only the last one on my Mac. Looks like the notification is always updated to the last message. But on the phone I can read all the messages from one person in one notification, not just the last message.

The same problem is for Google Messages and probably more apps.

**Comment by sannidhyaroy** [comment] 2024-09-21 18:48
Yeah, this is a known issue. This happens because your phone always sends the updated body of the notification to Soduto, which then updates the existing notification on your Mac's Notification Panel to the newer body.

The only thing that we can do is actually append the latest notification with the previous ones to form a list of messages, similar one that you see on your phone.

**Comment by sannidhyaroy** [comment] 2024-09-24 14:21
Closing this as it's a duplicate of #6

**Closed as completed by sannidhyaroy** 2024-09-24 14:21 UTC
Labels: enhancement
